"""add auth session

Revision ID: 124b502f3081
Revises: a3a6055b3f0
Create Date: 2014-03-16 15:35:04.574577

"""

# revision identifiers, used by Alembic.
revision = '124b502f3081'
down_revision = 'a3a6055b3f0'

from alembic import op
import sqlalchemy as sa
from atmcraft.model import meta



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_session')
    ### end Alembic commands ###
