"""initial revision

Revision ID: 12dfb5e5b43c
Revises: None
Create Date: 2013-09-08 11:51:39.060358

"""

# revision identifiers, used by Alembic.
revision = '12dfb5e5b43c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from atmcraft.model import meta



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=True),
    sa.Column('secret', meta.BcryptType(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance_type_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('last_trans_id', meta.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['balance_type_id'], ['balance_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_id', meta.GUID(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_balance_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_balance_id'], ['account_balance.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trans_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account_balance')
    op.drop_table('client')
    op.drop_table('balance_type')
    op.drop_table('account')
    ### end Alembic commands ###
