"""add unique constraint on client.identifier

Revision ID: 43cbfb862078
Revises: fe34cc9e6ae
Create Date: 2013-09-08 17:11:45.550954

"""

# revision identifiers, used by Alembic.
revision = '43cbfb862078'
down_revision = 'fe34cc9e6ae'

from alembic import op
import sqlalchemy as sa
from atmcraft.model import meta



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'uq_client_identifier', 'client', ['identifier'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'uq_client_identifier', 'client')
    ### end Alembic commands ###
