"""add unique constraint on client.identifier

Revision ID: 540dbbff3fd7
Revises: 46638dd48703
Create Date: 2014-02-10 15:27:34.622238

"""

# revision identifiers, used by Alembic.
revision = '540dbbff3fd7'
down_revision = '46638dd48703'

from alembic import op
import sqlalchemy as sa
from atmcraft.model import meta



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_client_identifier', 'client', ['identifier'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_identifier', 'client')
    ### end Alembic commands ###
