"""add unique constraint on client

Revision ID: a3a6055b3f0
Revises: 33bb7f3c67ff
Create Date: 2014-03-16 15:34:38.454567

"""

# revision identifiers, used by Alembic.
revision = 'a3a6055b3f0'
down_revision = '33bb7f3c67ff'

from alembic import op
import sqlalchemy as sa
from atmcraft.model import meta



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_client_identifier'), 'client', ['identifier'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_client_identifier'), 'client')
    ### end Alembic commands ###
