"""add auth session

Revision ID: fe34cc9e6ae
Revises: 3e6c0e32aabc
Create Date: 2013-09-08 13:16:03.417489

"""

# revision identifiers, used by Alembic.
revision = 'fe34cc9e6ae'
down_revision = '3e6c0e32aabc'

from alembic import op
import sqlalchemy as sa
from atmcraft.model import meta



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=u'fk_auth_session_account_id_account'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=u'fk_auth_session_client_id_client'),
    sa.PrimaryKeyConstraint('id', name=u'pk_auth_session')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_session')
    ### end Alembic commands ###
